name: hostelapplication
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+6

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:

  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  shared_preferences: 
  firebase_core: 
  firebase_auth: 
  cloud_firestore:
  firebase_storage: 
  uuid: ^4.4.2
  provider: ^6.0.3
  rflutter_alert:
  date_time_picker: 2.1.0
  image_picker: ^1.1.2
  file_picker:
  # image_downloader: ^0.31.0
  file: ^7.0.0
  auto_size_text: 3.0.0
  cached_network_image: ^3.3.1
  flutter_animate: ^4.5.0
  flutter_cache_manager: 3.3.2
  font_awesome_flutter: ^10.7.0
  from_css_color: 2.0.0
  google_fonts: 
  intl: 0.19.0
  json_path: ^0.7.2
  page_transition: ^2.1.0
  path_provider: ^2.1.3
  path_provider_android: ^2.2.7
  path_provider_foundation: ^2.4.0
  path_provider_platform_interface: ^2.1.2
  shared_preferences_android: ^2.2.3
  shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: ^2.3.2
  shared_preferences_web: ^2.3.0
  smooth_page_indicator: ^1.2.0
  sqflite: ^2.3.3+1
  timeago: ^3.7.0
  url_launcher: ^6.3.0
  url_launcher_android: ^6.3.3
  url_launcher_ios: ^6.3.1
  url_launcher_platform_interface: ^2.3.2
  grouped_list: ^6.0.0
  photo_view: ^0.15.0
  chat_bubbles: ^1.6.0
  # flutter_chat_ui: ^1.6.12


dependency_overrides:  
  intl: 0.17.0

dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/onboard/
    - shorebird.yaml
  
  fonts:
    - family: Brazila
      fonts:
        - asset: assets/onboard/Cirka_regular.ttf
        - asset: assets/onboard/Cirka_blod.otf
        - asset: assets/onboard/Cirka_light.otf
       
